# ================================================================================================
# This file specifies indices for the CSV files files of various parts. This is done to simplify
# access into and analysis of the data into those files.
# ================================================================================================

CPU_PROCESSOR_FAMILY, \
CPU_PROCESSOR_NUMBER, \
CPU_LAUNCH_DATE, \
CPU_LITHOGRAPHY, \
CPU_RECOMMENDED_PRICE, \
CPU_NO_OF_CORES, \
CPU_NO_OF_THREADS, \
CPU_BASE_FREQUENCY, \
CPU_MAX_TURBO_FREQUENCY, \
CPU_CACHE, \
CPU_TDP, \
CPU_MAX_MEMORY, \
CPU_MEMORY_TYPES, \
CPU_NO_OF_MEMORY_CHANNELS, \
CPU_MAX_MEMORY_BANDWIDTH, \
CPU_ECC_MEMORY_SUPPORT, \
CPU_GRAPHICS_BASE_FREQUENCY, \
CPU_GRAPHICS_MAX_FREQUENCY, \
CPU_GRAPHICS_MAX_MEMORY, \
CPU_GRAPHICS_OUTPUT, \
CPU_SUPPORT_4K, \
CPU_MAX_RESOLUTION_HDMI, \
CPU_MAX_RESOLUTION_DP, \
CPU_MAX_RESOLUTION_EDP, \
CPU_DIRECTX, \
CPU_OPENGL, \
CPU_PCIE, \
CPU_PCIE_CONFIG, \
CPU_MAX_PCIE_LANES, \
CPU_T, \
CPU_HT, \
CPU_ISA_EXTENSIONS, \
CPU_IDLE_STATES, \
CPU_THERMAL_MONITORING, \
CPU_SECURE_KEY, \
CPU_SOCKET, \
CPU_PERFORMANCE_SCORE = range(37)

GPU_ARCHITECTURE, \
GPU_BEST_RESOLUTION, \
GPU_BOOST_CLOCK, \
GPU_CORE_SPEED, \
GPU_DVI_CONNECTION, \
GPU_DIRECTX, \
GPU_DP_CONNECTION, \
GPU_HDMI_CONNECTION, \
GPU_L2_CACHE, \
GPU_MANUFACTURER, \
GPU_MAX_POWER, \
GPU_MEMORY, \
GPU_MEMORY_BANDWIDTH, \
GPU_MEMORY_BUS, \
GPU_MEMORY_SPEED, \
GPU_MEMORY_TYPE, \
GPU_NAME, \
GPU_OPEN_GL, \
GPU_PSU, \
GPU_PIXEL_RATE, \
GPU_PROCESS, \
GPU_RELEASE_PRICE, \
GPU_RESOLUTION, \
GPU_SLI_CROSSFIRE, \
GPU_SHADER, \
GPU_TEXTURE_RATE, \
GPU_VGA_CONNECTION, \
GPU_PERFORMANCE_SCORE = range(28)

MEMORY_CAS_LATENCY, \
MEMORY_ECC, \
MEMORY_HEAT_SPREADER, \
MEMORY_MANUFACTURER, \
MEMORY_NAME, \
MEMORY_PRICE_PER_GB, \
MEMORY_PRICES, \
MEMORY_SIZE, \
MEMORY_SPEED, \
MEMORY_IS_DDR4, \
MEMORY_DDR3_SPEED, \
MEMORY_DDR4_SPEED, \
MEMORY_DDR_SPEED, \
MEMORY_LAUNCHED,\
MEMORY_PERFORMANCE_SCORE = range(15)

STORAGE_CACHE, \
STORAGE_CAPACITY, \
STORAGE_HYBRID_SSD_CACHE, \
STORAGE_MANUFACTURER, \
STORAGE_NAME, \
STORAGE_POWER_LOSS_PROTECTION, \
STORAGE_PRICE_PER_GB, \
STORAGE_PRICES, \
STORAGE_RPM, \
STORAGE_IS_SSD, \
STORAGE_PERFORMANCE_SCORE = range(11)

MOTHERBOARD_CPU_SOCKET, \
MOTHERBOARD_CHIPSET, \
MOTHERBOARD_CROSSFIRE_SUPPORT, \
MOTHERBOARD_FORM_FACTOR, \
MOTHERBOARD_MANUFACTURER, \
MOTHERBOARD_MAXIMUM_SUPPORTED_MEMORY, \
MOTHERBOARD_MEMORY_TYPE, \
MOTHERBOARD_NAME, \
MOTHERBOARD_ONBOARD_ETHERNET, \
MOTHERBOARD_ONBOARD_USB3, \
MOTHERBOARD_ONBOARD_VIDEO, \
MOTHERBOARD_PRICES, \
MOTHERBOARD_RAID_SUPPORT, \
MOTHERBOARD_SLI_SUPPORT, \
MOTHERBOARD_LAUNCHED,\
MOTHERBOARD_PERFORMANCE_SCORE = range(16)
